import Card from "./Card";
import cardsDb from "./cards.json";

export const allCards = cardsDb as unknown as Card[];

export const basicLands = [
  "Plains",
  "Island",
  "Swamp",
  "Mountain",
  "Forest",
  "Snow-Covered Plains",
  "Snow-Covered Island",
  "Snow-Covered Swamp",
  "Snow-Covered Mountain",
  "Snow-Covered Forest",
];

export const bannedCards = [
  // this is a preview from MMQ
  "Crossbow Infantry",

  // ante cards
  "Amulet of Quoz",
  "Bronze Tablet",
  "Contract from Below",
  "Darkpact",
  "Demonic Attorney",
  "Jeweled Bird",
  "Rebirth",
  "Tempest Efreet",
  "Timmerian Fiends",

  // 'dexterity' cards
  "Chaos Orb",
  "Falling Star",
];

export const restrictedCards = [
  // power 9
  "Ancestral Recall",
  "Black Lotus",
  "Mox Emerald",
  "Mox Jet",
  "Mox Pearl",
  "Mox Ruby",
  "Mox Sapphire",
  "Time Walk",
  "Timetwister",

  // complete bullshit
  "Balance",
  "Berserk",
  "Black Vise",
  "Channel",
  "Fastbond",
  "Library of Alexandria",
  "Necropotence",
  "Sol Ring",
  "Strip Mine",

  // tutors
  "Demonic Consultation",
  "Demonic Tutor",
  "Enlightened Tutor",
  "Merchant Scroll",
  "Mystical Tutor",
  "Vampiric Tutor",
  "Worldly Tutor",

  // we are not Legacy
  "Dark Ritual",
  "Force of Will",
];

export const expandedVanillaCreatures = [
  "Abbey Gargoyles",
  "Abomination",
  "Adarkar Sentinel",
  "Aerathi Berserker",
  "Aesthir Glider",
  "Air Elemental",
  "Akron Legionnaire",
  "Ambush Party",
  "Amrou Kithkin",
  "An-havva Constable",
  "Anaba Bodyguard",
  "Angry Mob",
  "Archangel",
  "Arctic Foxes",
  "Ardent Militia",
  "Argothian Pixies",
  "Argothian Treefolk",
  "Aurochs",
  "Auspicious Ancestor",
  "Aysen Crusader",
  "Azimaet Drake",
  "Azure Drake",
  "Balduvian Barbarians",
  "Balduvian Bears",
  "Balduvian War-Makers",
  "Barbary Apes",
  "Barktooth Warbeard",
  "Battering Ram",
  "Bay Falcon",
  "Beast Walkers",
  "Beasts of Bogardan",
  "Benalish Hero",
  "Benalish Infantry",
  "Benalish Knight",
  "Bird Maiden",
  "Black Knight",
  "Blistering Barrier",
  "Bloodrock Cyclops",
  "Bog Imp",
  "Bog Rats",
  "Bog Wraith",
  "Bone Shaman",
  "Brass Man",
  "Brassclaw Orcs",
  "Breathstealer",
  "Breezekeeper",
  "Bronze Horse",
  "Brushwagg",
  "Burning Shield Askari",
  "Cadaverous Knight",
  "Camel",
  "Canopy Dragon",
  "Carnivorous Plant",
  "Carrion Ants",
  "Cat Warriors",
  "Cemetery Gate",
  "Cerulean Wyvern",
  "Chub Toad",
  "Clay Statue",
  "Clergy of the Holy Nimbus",
  "Cloud Djinn",
  "Cloud Elemental",
  "Cockatrice",
  "Colossus of Sardia",
  "Crash of Rhinos",
  "Craw Giant",
  "Craw Wurm",
  "Crimson Kobolds",
  "Crimson Roc",
  "Crookshank Kobolds",
  "Crystal Golem",
  "Cyclopean Mummy",
  "Dakkon Blackblade",
  "Dancing Scimitar",
  "Dandan",
  "Deadly Insect",
  "Death Speakers",
  "Desert Nomads",
  "Devouring Deep",
  "Diabolic Machine",
  "Dire Wolves",
  "Dirtwater Wraith",
  "Dragon Engine",
  "Drift of the Dead",
  "Drowned",
  "Drudge Skeletons",
  "Durkwood Boards",
  "Duskrider Falcon",
  "Dwarven Berserker",
  "Dwarven Soldier",
  "Dwarven Trader",
  "Earth Elemental",
  "Ebony Rhino",
  "Ekundu Cyclops",
  "Ekundu Griffin",
  "El-Hajjaj",
  "Elder Land Wurm",
  "Elven Riders",
  "Elvish Archers",
  "Elvish Bard",
  "Elvish Ranger",
  "Emerald Dragonfly",
  "Enchanted Begin",
  "Enslaved Scout",
  "Eron the Relentless",
  "Evil Eye of Orms-By-Gore",
  "Fallen Askari",
  "Femeref Knight",
  "Femeref Scouts",
  "Feral Shadow",
  "Fetid Horror",
  "Fire Drake",
  "Fire Elemental",
  "Flame Spirit",
  "Flying Men",
  "Folk of An-havva",
  "Folk of the Pines",
  "Foriysian Brigade",
  "Freewind Falcon",
  "Frost Giant",
  "Frozen Shade",
  "Fyndhorn Druid",
  "Gabriel Angelfire",
  "Gaea's Avenger",
  "Ghost Hounds",
  "Ghost Ship",
  "Giant Mantis",
  "Giant Shark",
  "Giant Slub",
  "Giant Spider",
  "Giant Tortoise",
  "Giant Turtle",
  "Gibbering Hyenas",
  "Glacial Wall",
  "Goblin Balloon Brigade",
  "Goblin Elite Infantry",
  "Goblin Flotilla",
  "Goblin Hero",
  "Goblin Mutant",
  "Goblins of the Flarg",
  "Gorilla Berserkers",
  "Gorilla Chieftain",
  "Gorilla Pack",
  "Granite Gargoyle",
  "Gray Ogre",
  "Grizzled Wolverine",
  "Grizzly Bears",
  "Haunting Apparition",
  "Hazerider Drake",
  "Headless Horseman",
  "Hill Giant",
  "Hipparion",
  "Hoar Shade",
  "Homarid Warrior",
  "Hornet Cobra",
  "Horrible Hordes",
  "Hulking Cyclops",
  "Hunding Gjornersen",
  "Hurloon Minotaur",
  "Hyalopterous Lemure",
  "Icatian Infantry",
  "Icatian Phalanx",
  "Icatian Skirmishers",
  "Igneous Golem",
  "Ihsan's Shade",
  "Infernal Medusa",
  "Iron Tusk Elephant",
  "Ironclaw Orcs",
  "Ironroot Treefolk",
  "Jasmine Boreal",
  "Jedit Ojanen",
  "Jerrard of the Closed Fist",
  "Johtull Wurm",
  "Jolrael's Centaur",
  "Joven's Ferrets",
  "Juggernaut",
  "Jungle Troll",
  "Jungle Wurm",
  "Karoo Meerkat",
  "Kasimir the Lone Wolf",
  "Keeper of Kookus",
  "Keepers of the Faith",
  "Keldon Warlord",
  "Killer Bees",
  "King Cheetah",
  "Kird Ape",
  "Kjeldoran Escort",
  "Kjeldoran Frostbeast",
  "Kjeldoran Knight",
  "Kjeldoran Phalanx",
  "Kjeldoran Skycaptain",
  "Kjeldoran Skyknight",
  "Kjeldoran Warrior",
  "Knight of Stromgald",
  "Knight of Valor",
  "Knights of Thorn",
  "Kobolds of Kher Keep",
  "Labyrinth Minotaur",
  "Lady Orca",
  "Land Leeches",
  "Lead Golem",
  "Leaping Lizard",
  "Legions of Lim-Dul",
  "Leviathan",
  "Lhurgoyf",
  "Lim-Dul's Cohort",
  "Lim-Dul's High Guard",
  "Living Wall",
  "Livonya Silone",
  "Locust Swarm",
  "Longbow Archer",
  "Lost Soul",
  "Lurker",
  "Mahamoti Djinn",
  "Manta Ray",
  "Marble Priest",
  "Marhault Elsdragon",
  "Maro",
  "Marsh Goblins",
  "Melesse Spirit",
  "Mercenaries",
  "Merfolk of the Pearl Trident",
  "Merfolk Raiders",
  "Mesa Falcon",
  "Mesa Pegasus",
  "Mijae Djinn",
  "Mischievious Poltergeist",
  "Mist Dragon",
  "Mons's Goblin Raiders",
  "Moor Fiend",
  "Moorish Cavalry",
  "Moss Monster",
  "Mountain Goat",
  "Mountain Yeti",
  "Mtenda Herder",
  "Mtendo Lion",
  "Narwhal",
  "Nightmare",
  "Noble Elephant",
  "Obsianus Golem",
  "Ogre Enforcer",
  "Onulet",
  "Orcish Conscripts",
  "Orcish Veteran",
  "Order of Leitbur",
  "Order of the Ebon Hand",
  "Order of the White Shield",
  "Orgg",
  "Ornithopter",
  "Pale Bears",
  "Panther Warriors",
  "Patagia Golem",
  "Pavel Maliki",
  "Pearl Dragon",
  "Pearled Unicorn",
  "People of the Woods",
  "Pestilence Rats",
  "Phantasmal Fiend",
  "Phantom Monster",
  "Phantom Warrior",
  "Phyrexian Walker",
  "Pikemen",
  "Plague Rats",
  "Primal Clay",
  "Pygmy Allosaurus",
  "Python",
  "Rabid Wombat",
  "Radiant Essence",
  "Raging Bull",
  "Raging Gorilla",
  "Raging Spirit",
  "Rainbow Efreet",
  "Ramirez DiPietro",
  "Rashka the Slayer",
  "Razortooth Rats",
  "Redwood Treefolk",
  "Repentant Blacksmith",
  "Restless Dead",
  "Righteous Avengers",
  "Rime Dryad",
  "River Boa",
  "River Merfolk",
  "Roc of Kher Ridges",
  "Rock Basilisk",
  "Root Spider",
  "Roterothopter",
  "Sabretooth Tiger",
  "Sandbar Crocodile",
  "Savannah Lions",
  "Scalebane's Elite",
  "Scaled Wurm",
  "Scarwood Goblins",
  "Scathe Zombies",
  "Scryb Sprites",
  "Sea Serpent",
  "Sea Spirit",
  "Sea Sprite",
  "Sea Troll",
  "Searing Spear Askari",
  "Sedge Troll",
  "Segovian Leviathan",
  "Serra Angel",
  "Serra Inquisitors",
  "Shadow Rider",
  "Shambling Strider",
  "Shanodin Dryads",
  "Shapeshifter",
  "Shield Bearer",
  "Shivan Dragon",
  "Shyft",
  "Silver Erne",
  "Sir Shandlar of Eberyn",
  "Sivitri Scarzam",
  "Skulking Ghost",
  "Sol'kanar the Swamp King",
  "Spectral Bears",
  "Spirit of the Night",
  "Spitting Drake",
  "Spitting Slug",
  "Squire",
  "Stalking Tiger",
  "Stone Spirit",
  "Storm Crow",
  "Storm Shaman",
  "Su-Chi",
  "Sunweb",
  "Suq'Ata Lancer",
  "Talruum Champion",
  "Talruum Minotaur",
  "Talruum Piper",
  "Tar Pit Warrior",
  "Tarpan",
  "Teeka's Dragon",
  "Teferi's Drake",
  "Teferi's Honor Guard",
  "Tempest Drake",
  "Teremko Griffin",
  "The Lady of the Mountain",
  "Thicket Basilisk",
  "Thunder Spirit",
  "Thunder Wall",
  "Timber Wolves",
  "Tobias Andrion",
  "Tolarian Drake",
  "Tor Giant",
  "Torsten Von Ursus",
  "Tundra Wolves",
  "Two-headed Giant of Foriys",
  "Uncle Istvan",
  "Urza's Avenger",
  "Urza's Engine",
  "Uthden Troll",
  "Vampire Bats",
  "Veldrane of Sengir",
  "Viashino Warrior",
  "Viashivan Dragon",
  "Vodalian Knights",
  "Vodalian Soldiers",
  "Volcanic Dragon",
  "Walking Dead",
  "Walking Wall",
  "Wall of Air",
  "Wall of Bone",
  "Wall of Brambles",
  "Wall of Caltrops",
  "Wall of Dust",
  "Wall of Earth",
  "Wall of Fire",
  "Wall of Heat",
  "Wall of Ice",
  "Wall of Lava",
  "Wall of Light",
  "Wall of Opposition",
  "Wall of Pine Needles",
  "Wall of Putrid Flesh",
  "Wall of Shadows",
  "Wall of Shields",
  "Wall of Spears",
  "Wall of Stone",
  "Wall of Swords",
  "Wall of Tombstones",
  "Wall of Vapor",
  "Wall of Water",
  "Wall of Wonder",
  "Wall of Wood",
  "War Elephant",
  "War Mammoth",
  "Warthog",
  "Water Elemental",
  "Water Wurm",
  "White Knight",
  "Wild Aesthir",
  "Wild Elephant",
  "Wildfire Emissary",
  "Will-O'-The-Wisp",
  "Willow Faerie",
  "Wind Spirit",
  "Windreaper Falcon",
  "Wolverine Pack",
  "Woolly Mammoths",
  "Woolly Spider",
  "Yavimaya Gnats",
  "Yavmiaya Ancients",
  "Ydwen Efreet",
  "Yotian Soldier",
  "Zebra Unicorn",
  "Zephyr Falcon",
  "Zhalfirin Knight",
];
